base_packages:                  #Наименование пакетов для установки
  - curl
  - wget
  - vim
  - htop
  - net-tools
  - tree
  - jq
  - git
  - ufw
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - git

timezone: "Europe/Moscow"         #Тайм-зона

ufw_ports:                        #Прописанные порты которые будут открыты
  - 22    # SSH
  - 6443  # Kubernetes API
  - 2379  # etcd
  - 10250 # Kubelet API
  - 10259 # kube-scheduler
  - 10257 # kube-controller-manager
  - 8080  # web
  - 7946
  - 30442
  - 32710
  - 8472  # VXLAN
  - 179   # BGP Calico
  - 9100  #Prometheus metrics
  - 10249 #Metrics

additional_ssh_keys:             #Pubkey хоста который тоже хочет подключиться к серверам
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcQDcvGbjUNMWZRyaooxgDo0/CFAwWyLzq2ISdK8rQXzmyxKO09iM5cE9C+580+4SPQREWeSM7w+ez9pzHRafIB9l7kaWGxym8flOJVMRo0zyanYvyMSaBD5a9vfs35U2aW+qplQ/Ml5p+k6oFWrlKHtSY/NPe0wLXhYtvElqtfdS2vD6jywCJ4YodBI0c1pKZH2ZGhwWYL9F2c7lFRKK0C6dHRmccgRTJrkPNYXTaVP5Ba29cbfeM8BoGdFmk3lxs63+R+5roEqz+EBh3BMlqqMYyGMykswkUzVkCiIliAHo2rejksp5PEX1cQrj8ZYXggsOWip9f8GP8Rwjd7lHykkEeOPYgGQL9Ut6I0B26/j3hCqneog1A3C2cv2iRmJsbjhxs8WgFwCsXxs8kRJK4ghJ7C2NooZTIKiV2tQsuedehW3GOWKLaIP/glt9tyz8/4pzzxr/jRKovR5JrKHTYHu9BClwtZE7jstw6TcwK/RecYLxShkmOwNVGPrsFhuxN8m5hQRGcVGn2WEeRVY9lWB2+7c8xXrL9//j61OzsY/oKEu5eWr9NaKfSeSxMHiTFFRUH1HFJ6DfeiM8C6X6LEVN7ZZGkVqEsO0oKZi1PLJKmm6po2Oi7QxM2GeLHMoAe+czjWtIH3l33inyG7Mn8kQ5YP2yOGVE8aMG8OdfkNQ== grandauto\andrey.gurenich@gurenich_IT"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuekjTfysXmefE7STAZ44dZJ5n3BbZkPoqNC3WNeylA+Es2xfmJouVYRWOz4c+NkLENi5DDQh9nCYle0+U0TRtIqFKEqRE1VmfJTSinbCn/w/N/APoPZhkVMK5nlUgUkeQRrcqJaLSRpIxcpf+4/caAbhfvFq1n0Xyt5QnKQ+MJ9s6BZyk/Aghz4zCJVxDSa0PY3QvXgKpJqDU4C4ys8AE7HWStaDz5z6FQ1iG2cT2hh+pgsY0BDbNISXciJ9f42WoYmSrQqVrfgRqu3z+H22esQ7vTEVl8mx3VS7mvdzbrEdOnrS7qOoiH/u11bktIeSi5CH5nx++ht7USUEfAJ+urgFc0FNGjvx68ZbRqbyk453SCNRtDNAvu5YFduz64ffl4Z84rr65LLTYu4HpyAklD4QNgH0pq+eqektTd/msr9zL4w9K7CAxlgVCO7woskx8WQcGIhuX6ZUPd/OVk7jVoSEOi3uGXOGcE4eX6UrywGf+0mz4l2UUaAfcAgs0By0= sysadmin@AnsibleServer"
