apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: 01-infrastructure
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus-stack
spec:
  groups:
  - name: disk-alerts
    rules:
    - alert: TestDiskSpace
      expr: 100 * (1 - (node_filesystem_avail_bytes{mountpoint="/", fstype!="tmpfs"} / node_filesystem_size_bytes{mountpoint="/", fstype!="tmpfs"})) > 40
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "ТЕСТ: Мало места на диске на ноде {{ $labels.instance }}"
        description: "ТЕСТ: Использовано {{ $value | humanize }}%"
  - name: memory-alerts
    rules:
    # Высокое использование памяти (>50%)
    - alert: NodeMemoryUsageHigh
      expr: |
        (
          1 -
          node_memory_MemAvailable_bytes
          /
          node_memory_MemTotal_bytes
        ) * 100 > 50
      for: 5m
      labels:
        severity: warning
        category: infrastructure
      annotations:
        summary: "Высокое использование памяти на ноде"
        description: |
           Нода: {{ $labels.instance }}
           Использовано памяти: {{ printf "%.1f" $value }}%
           Всего памяти: {{ humanize $value }}%
